namespace TheUtils.SourceGenerator;

using System.Linq;

public class GenInterfaceSourcesGenerator
{
    public static string GenerateDelegates(ClassMetadata meta)
    {
        var outerClassBegin =
            meta.ParentClassName != null
                ? $"public {(meta.ParentClassIsStatic ? "static" : "")} partial class {meta.ParentClassName} {{"
                : "";

        var outerClassEnd = meta.ParentClassName != null ? "}" : "";

        var methods = string.Join(
            "\n",
            meta.Methods.Select(meth =>
            {
                var inputParams = string.Join(
                    ", ",
                    meth.Parameters.Select(p =>
                        $"{p.TypeName} {p.Name} {(p.IsDefault ? p.Default : "")}"
                    )
                );

                return @$"
        /// <summary>
        /// <inheritdoc cref=""{meta.ClassName}.{meth.Name}"" />
        /// </summary>
        {meth.ReturnType} {meth.Name}{meth.TypeParameters}(
            {inputParams}
        ){meth.TypeConstraints};
                ";
            })
        );

        return @$"// <auto-generated />
#pragma warning disable

namespace {meta.NamespaceName}
{{
    {outerClassBegin}

    /// <summary>
    /// <inheritdoc cref=""{meta.ClassName}""/>
    /// </summary>
    public interface I{meta.ClassName}{meta.TypeParameters}{meta.TypeConstraints}
    {{
        {methods}
    }}

    public partial class {meta.ClassName}{meta.TypeParameters} : I{meta.ClassName}{meta.TypeParameters}{meta.TypeConstraints} {{ }}

    {outerClassEnd}
}}
";
    }
}
